### ISSUE TITLE
Release: TikiClient.ui

### ISSUE THREAD

**Issue by ricardobrg** [tiki/publish-client-ios#31]
### Reason

Enable the pre-built UIs to the user

### Description

TikiClient UI

### Success Criteria

- [x] tiki/publish-client-ios/issues/15
- [x] tiki/publish-client-ios/issues/16
- [x] tiki/publish-client-ios/issues/16
- [x] tiki/publish-client-ios/issues/17
- [x] tiki/publish-client-ios/issues/18
- [x] tiki/publish-client-ios/issues/19
